apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80   # Port exposed externally by the service
    targetPort: 3001  # Port your backend application listens on within the pods
