apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432   # Port exposed externally by the service
    targetPort: 5432  # Port PostgreSQL listens on within the pods
