version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/book_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000 for frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Map container port 3001 to host port 3001 for backend
    environment:
      - POSTGRES_HOST=db
      # Other backend environment variables
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432 for PostgreSQL
    command: ["postgres", "-c", "log_statement=all"]  # Optional: log all SQL statements

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"  # Map container port 80 to host port 5050 for pgAdmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: your_email@example.com
  #     PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password

volumes:
  postgres_data:
